headings: ['Off', 'Gun-10', 'VELA Quads', 'Dipoles', 'Correctors', 'CLARA PH1 BPMs', 'Custom']
frequencies: [1, 5, 10, 25, 50, 100]
magnets:
  'Gun-10':
    Names: [
    ['CLA-GUN-LRF-CTRL-01:vm:dsp:ff_amp:amplitude','RF Amplitude'],
    ['CLA-GUN-LRF-CTRL-01:ad1:ch1:power_remote_s.POWER','KLY FWD Power'],
    ['CLA-LRG1-VAC-IONP-01:P','IONP-01 Pressure'],
    ['CLA-LRG1-VAC-IONP-02:P','IONP-02 Pressure'],
    ['CLA-LRG1-VAC-IMG-01:P','IMG-01 Pressure'],
    ['CLA-GUN-RF-LRRG-01:RT','Gun Temperature'],
    ['CLA-GUN-LRF-CTRL-01:ad1:ch3:power_remote_s.POWER','GUN FWD Power'],
    ['CLA-GUN-LRF-CTRL-01:ad1:ch4:power_remote_s.POWER','GUN REV Power'],
    ]
    PVs:
      RI: 'custom'
  Correctors:
    Names: [HCOR01, HCOR02, HCOR03, HCOR04, HCOR05, HCOR06, HCOR07, HCOR08, HCOR09,
      HCOR10, HCOR11, VCOR01, VCOR02, VCOR03, VCOR04, VCOR05, VCOR06, VCOR07, VCOR08,
      VCOR09, VCOR10, VCOR11]
    PVs:
      RI: ['', getRI]
      SI: ['', getSI]
  Dipoles:
    Names: [DIP01, DIP02, DIP03]
    PVs:
      RI: ['', getRI]
      SI: ['', getSI]
  'Off':
    Names: []
    PVs: {}
  VELA Quads:
    Names: [QUAD01, QUAD02, QUAD03, QUAD04, QUAD05, QUAD06, QUAD07, QUAD08, QUAD09,
      QUAD10, QUAD11, QUAD12, QUAD13, QUAD14, QUAD15]
    PVs:
      RI: ['self.VELAMagnets', getRI]
      SI: ['self.VELAMagnets', getSI]
  CLARA PH1 BPMs:
    Names: [S01-BPM01, S02-BPM01, S02-BPM02, C2V-BPM01]
    PVs:
      X: ['self.bpms', getXFromPV]
      Y: ['self.bpms', getYFromPV]
